WITH src(name) AS (VALUES
  ('2B'),
  ('AAIB'),
  ('AL Doha Foods'),
  ('Abou Ghali motors'),
  ('Alahly Sabbour'),
  ('Alarabia Group'),
  ('Aldawlia For Plastic Materials'),
  ('Alsafy group'),
  ('Aman Holding'),
  ('Arma Group'),
  ('Asfour crystal'),
  ('Attssal'),
  ('Axis'),
  ('Bedinroom'),
  ('Cairo 3A'),
  ('Concrete'),
  ('Crossworkers-Egypt'),
  ('Dabur'),
  ('Damen e payment'),
  ('Delta Masr Group'),
  ('Delta lighting'),
  ('EGMI group'),
  ('EYouth'),
  ('Eden/phase2'),
  ('Etisal'),
  ('Fort Capital group'),
  ('Gardenia'),
  ('Garnell'),
  ('Groovy Aesthetic clinics'),
  ('Hassan Allam Holding'),
  ('Illa'),
  ('Indomie egypt'),
  ('Innovasights'),
  ('Kahraba'),
  ('Kandil Glass'),
  ('Komandas HUB'),
  ('Kortech'),
  ('Larz Developments'),
  ('MKY'),
  ('Madaar Developments'),
  ('Madient Masr'),
  ('Mahgoub'),
  ('Mansour Group'),
  ('Mavens Consulting'),
  ('Metro Markets'),
  ('Mevac'),
  ('Misr alkeir'),
  ('Mobco'),
  ('Moneyfellows'),
  ('Monglish'),
  ('Nahdet Misr Group'),
  ('Nawy'),
  ('Nok'),
  ('Organo Group'),
  ('Paymob'),
  ('Pyramakerz'),
  ('Reckitt'),
  ('Red square'),
  ('Rock Developments'),
  ('Rushbrush'),
  ('Savola'),
  ('Sectors Construction'),
  ('Seoudi'),
  ('Sharapet'),
  ('Shift-ev'),
  ('Sky holding'),
  ('Spinnyes'),
  ('TBS'),
  ('TLD'),
  ('Tagaddod'),
  ('Talent360'),
  ('Taskeen Egypt'),
  ('Techlaz'),
  ('Tracks'),
  ('VXI'),
  ('Yes Pac Packaging Solutions'),
  ('Zahran Markets'),
  ('Zero Carbon'),
  ('bosta'),
  ('egyproperty'),
  ('elsewedy-ind'),
  ('enableoutsourcing'),
  ('hebasaid1989@gmail.com'),
  ('hudel'),
  ('kedma dhd'),
  ('max360'),
  ('midea group'),
  ('onecard'),
  ('orion'),
  ('outsourcy'),
  ('saudia catering'),
  ('skyline'),
  ('wadi Group'),
  ('widebot')
)
SELECT
  s.name AS import_name,
  a.id   AS existing_id,
  a.name AS existing_name,
  a.am_mail AS existing_owner,
  a.stage::text AS existing_stage,
  a.merged_into IS NOT NULL AS is_merged
FROM src s
JOIN accounts a ON lower(trim(a.name)) = lower(trim(s.name))
ORDER BY s.name;