-- Mariam Accounts import (94 rows) — generated 2026-06-30
UPDATE accounts SET am_mail='mariam.samir@recruitera.ai', owner_id='f494e81a-81c6-4e2a-ba7d-1366dbd9ef62'::uuid
WHERE lower(trim(name)) = 'sectors construction';

CREATE TEMP TABLE _import (
  company text, contact_name text, contact_phone text, source text,
  notes text, stage text, is_disq boolean, disq_reason text,
  proposed_amount numeric, deadline date, has_trial boolean,
  conversion_date date, amount numeric, plan_tier text,
  raw_extra jsonb, sheet_date date
) ON COMMIT DROP;
INSERT INTO _import VALUES
  ('Aman Holding', 'yasmin', '+201092010040', NULL, '-They require more than 80 users.
 
-They need the Blue Collar module.

-They need the MPP module.  Ahmed Hamdy', 'lost', true, 'Unreachable', 124000.0, '2025-11-30'::date, false, NULL, NULL, NULL, '{"imported_from": "Mariam Accounts (3).xlsx", "import_date": "2026-06-28", "comm": "Call", "using_ats": "No", "ats_name": null, "proposed_plan": "Enterprise", "demo_status": null, "invoiced": false, "collected": false}'::jsonb, '2025-09-11'::date),
  ('AAIB', 'nader basha', '+201220673708', 'Hub Spot — Old Data', 'We have a meeting next Sunday, and we expect to receive the approval within three weeks.', 'mql', false, NULL, 485000.0, '2026-06-30'::date, false, NULL, NULL, NULL, '{"imported_from": "Mariam Accounts (3).xlsx", "import_date": "2026-06-28", "comm": "Call", "using_ats": "No", "ats_name": null, "proposed_plan": "Enterprise+", "demo_status": null, "invoiced": false, "collected": false}'::jsonb, NULL),
  ('Illa', 'fatma', '+201127978902', NULL, 'They are currently using Zoho at a lower price (20.000)and are not willing to pay more at this time', 'lost', true, 'Pricing', 60000.0, '2025-10-15'::date, false, NULL, NULL, 'Pro', '{"imported_from": "Mariam Accounts (3).xlsx", "import_date": "2026-06-28", "comm": "Call", "using_ats": "Yes", "ats_name": "Zoho", "proposed_plan": "Pro", "demo_status": null, "invoiced": false, "collected": false}'::jsonb, NULL),
  ('Cairo 3A', 'mohamed khalifa', '+201225513552', 'BD iCareer', 'unreachable', 'lost', true, 'Unreachable', 124000.0, '2025-10-15'::date, false, NULL, NULL, NULL, '{"imported_from": "Mariam Accounts (3).xlsx", "import_date": "2026-06-28", "comm": "Call", "using_ats": "No", "ats_name": null, "proposed_plan": "Enterprise", "demo_status": null, "invoiced": false, "collected": false}'::jsonb, NULL),
  ('Zahran Markets', 'ayman', '+201212223183', 'Hub Spot — Old Data', 'unreachable', 'lost', true, 'Unreachable', 124000.0, '2025-09-30'::date, false, NULL, NULL, NULL, '{"imported_from": "Mariam Accounts (3).xlsx", "import_date": "2026-06-28", "comm": "Call", "using_ats": "No", "ats_name": null, "proposed_plan": "Enterprise", "demo_status": null, "invoiced": false, "collected": false}'::jsonb, NULL),
  ('2B', 'peter', '+201021053844', 'LinkedIn', 'They have changed their mind and decided not to proceed with paying for the ATS.', 'lost', true, 'Pricing', 124000.0, '2025-10-26'::date, false, NULL, NULL, NULL, '{"imported_from": "Mariam Accounts (3).xlsx", "import_date": "2026-06-28", "comm": "Call", "using_ats": "No", "ats_name": null, "proposed_plan": "Enterprise", "demo_status": null, "invoiced": false, "collected": false}'::jsonb, NULL),
  ('Moneyfellows', 'Yasmin algazar', '+201120797999', 'Hub Spot — Old Data', 'Most likely, they have renewed with Workable', 'lost', true, 'Unreachable', 124000.0, '2025-09-30'::date, true, NULL, NULL, NULL, '{"imported_from": "Mariam Accounts (3).xlsx", "import_date": "2026-06-28", "comm": "Call", "using_ats": "Yes", "ats_name": "Workable", "proposed_plan": "Enterprise", "demo_status": null, "invoiced": false, "collected": false}'::jsonb, NULL),
  ('Komandas HUB', 'yosra', '+201202228157', 'Hub Spot — Old Data', NULL, 'lost', true, 'Unreachable', 60000.0, '2025-09-30'::date, false, NULL, NULL, NULL, '{"imported_from": "Mariam Accounts (3).xlsx", "import_date": "2026-06-28", "comm": "Call", "using_ats": "No", "ats_name": null, "proposed_plan": "Pro", "demo_status": null, "invoiced": false, "collected": false}'::jsonb, NULL),
  ('Monglish', 'mahmoud', '+201011575726', 'Hub Spot — Old Data', NULL, 'mql', true, 'No Budget', 124000.0, '2025-10-26'::date, false, NULL, NULL, NULL, '{"imported_from": "Mariam Accounts (3).xlsx", "import_date": "2026-06-28", "comm": "Call", "using_ats": "No", "ats_name": null, "proposed_plan": "Enterprise", "demo_status": null, "invoiced": false, "collected": false}'::jsonb, NULL),
  ('Kandil Glass', 'hend sayed', '+201070900854', 'LinkedIn', 'she is waiting for management approval', 'mql', false, NULL, 124000.0, '2025-10-30'::date, true, NULL, NULL, 'Enterprise', '{"imported_from": "Mariam Accounts (3).xlsx", "import_date": "2026-06-28", "comm": "Call", "using_ats": "No", "ats_name": null, "proposed_plan": "Enterprise", "demo_status": null, "invoiced": false, "collected": false}'::jsonb, NULL),
  ('Attssal', 'nada elshawadfy', '+10000858338', 'Wuzzuf', 'on hold', 'lost', true, 'No Budget', 60000.0, '2025-10-30'::date, false, NULL, NULL, NULL, '{"imported_from": "Mariam Accounts (3).xlsx", "import_date": "2026-06-28", "comm": "Call", "using_ats": "No", "ats_name": null, "proposed_plan": "Pro", "demo_status": null, "invoiced": false, "collected": false}'::jsonb, NULL),
  ('Mansour Group', 'habiba', '+201112930033', 'Hub Spot — Old Data', NULL, 'lost', true, 'Unreachable', 124000.0, '2025-10-30'::date, false, NULL, NULL, NULL, '{"imported_from": "Mariam Accounts (3).xlsx", "import_date": "2026-06-28", "comm": "Call", "using_ats": "No", "ats_name": null, "proposed_plan": "Enterprise", "demo_status": null, "invoiced": false, "collected": false}'::jsonb, NULL),
  ('Eden/phase2', 'haidy kamel', '+201010080274', 'Hub Spot — Old Data', 'We will schedule a meeting next week to discuss the next phase.', 'mql', false, NULL, 200000.0, NULL, false, NULL, NULL, NULL, '{"imported_from": "Mariam Accounts (3).xlsx", "import_date": "2026-06-28", "comm": "Call", "using_ats": "No", "ats_name": null, "proposed_plan": "Enterprise+", "demo_status": null, "invoiced": false, "collected": false}'::jsonb, NULL),
  ('orion', 'nwesri', '+201200720111', 'Renewal', 'We are waiting for the meeting next week in order to obtain the approval.', 'mql', true, 'Global Deal', 122000.0, '2025-11-15'::date, false, NULL, NULL, NULL, '{"imported_from": "Mariam Accounts (3).xlsx", "import_date": "2026-06-28", "comm": "Call", "using_ats": "Yes", "ats_name": "Recruitera", "proposed_plan": "Enterprise", "demo_status": null, "invoiced": false, "collected": false}'::jsonb, NULL),
  ('Taskeen Egypt', 'eman ayman', '+201205544524', NULL, 'hold to the end of the year', 'lost', true, 'Global Deal', 124000.0, '2025-06-11'::date, false, NULL, NULL, NULL, '{"imported_from": "Mariam Accounts (3).xlsx", "import_date": "2026-06-28", "comm": "Call", "using_ats": "Yes", "ats_name": "Zoho", "proposed_plan": "Enterprise", "demo_status": null, "invoiced": false, "collected": false}'::jsonb, NULL),
  ('TBS', 'mona adel', '+201225106544', 'Hub Spot — Old Data', 'no budget', 'lost', true, 'Pricing', 60000.0, '2025-10-30'::date, false, NULL, NULL, NULL, '{"imported_from": "Mariam Accounts (3).xlsx", "import_date": "2026-06-28", "comm": "Call", "using_ats": "No", "ats_name": null, "proposed_plan": "Free/CFYE", "demo_status": null, "invoiced": false, "collected": false}'::jsonb, NULL),
  ('Tagaddod', 'menna', '+201222277666', 'LinkedIn', NULL, 'mql', true, 'Unreachable', NULL, NULL, true, NULL, NULL, NULL, '{"imported_from": "Mariam Accounts (3).xlsx", "import_date": "2026-06-28", "comm": "Call", "using_ats": "Yes", "ats_name": "Workable", "proposed_plan": null, "demo_status": null, "invoiced": false, "collected": false}'::jsonb, NULL),
  ('Etisal', 'mohamed magdi', '+201009175405', 'BD iCareer', NULL, 'won', false, NULL, 150000.0, '2025-10-11'::date, false, '2025-11-16'::date, 150000.0, 'Enterprise', '{"imported_from": "Mariam Accounts (3).xlsx", "import_date": "2026-06-28", "comm": "Call", "using_ats": "No", "ats_name": null, "proposed_plan": "Free/CFYE", "demo_status": null, "invoiced": false, "collected": true}'::jsonb, NULL),
  ('Spinnyes', 'abdelrahman ezzat', '+201118155883', 'LinkedIn', NULL, 'won', false, NULL, 124000.0, NULL, false, '2025-11-26'::date, 124000.0, 'Enterprise', '{"imported_from": "Mariam Accounts (3).xlsx", "import_date": "2026-06-28", "comm": "Call", "using_ats": "Yes", "ats_name": "MenaTech", "proposed_plan": "Free/CFYE", "demo_status": null, "invoiced": false, "collected": true}'::jsonb, NULL),
  ('Misr alkeir', 'abeer eissa', '+201004455932', 'LinkedIn', NULL, 'mql', true, 'Unreachable', 124000.0, '2025-11-15'::date, false, NULL, NULL, NULL, '{"imported_from": "Mariam Accounts (3).xlsx", "import_date": "2026-06-28", "comm": "Call", "using_ats": "No", "ats_name": null, "proposed_plan": "Enterprise", "demo_status": null, "invoiced": false, "collected": false}'::jsonb, NULL),
  ('Paymob', 'nesma ghazi', '+201228080480', 'LinkedIn', NULL, 'won', false, NULL, 204000.0, '2025-12-30'::date, true, '2025-12-03'::date, 204000.0, 'Enterprise', '{"imported_from": "Mariam Accounts (3).xlsx", "import_date": "2026-06-28", "comm": "Call", "using_ats": "No", "ats_name": null, "proposed_plan": "Enterprise", "demo_status": null, "invoiced": true, "collected": false}'::jsonb, NULL),
  ('Mevac', 'ahmed fathy', '+201000199736', 'Upgrade', NULL, 'lost', true, 'Pricing', 72000.0, '2025-11-15'::date, false, NULL, NULL, 'Enterprise', '{"imported_from": "Mariam Accounts (3).xlsx", "import_date": "2026-06-28", "comm": "Call", "using_ats": "Yes", "ats_name": "Recruitera", "proposed_plan": "Enterprise", "demo_status": null, "invoiced": false, "collected": false}'::jsonb, NULL),
  ('Arma Group', 'samar', '+201003304222', 'LinkedIn', NULL, 'lost', true, 'Unreachable', 124000.0, '2025-11-30'::date, false, NULL, NULL, 'Enterprise', '{"imported_from": "Mariam Accounts (3).xlsx", "import_date": "2026-06-28", "comm": "Call", "using_ats": "No", "ats_name": null, "proposed_plan": "Enterprise", "demo_status": null, "invoiced": false, "collected": false}'::jsonb, NULL),
  ('Aldawlia For Plastic Materials', 'waled saeed', '+201044097001', 'Forasna', NULL, 'mql', false, NULL, NULL, NULL, false, NULL, NULL, NULL, '{"imported_from": "Mariam Accounts (3).xlsx", "import_date": "2026-06-28", "comm": "Call", "using_ats": null, "ats_name": null, "proposed_plan": null, "demo_status": "No Show", "invoiced": false, "collected": false}'::jsonb, '2025-11-06'::date),
  ('Savola', 'noha masry', '+201158529339', 'LinkedIn', NULL, 'lost', true, 'Unreachable', NULL, '2025-11-30'::date, false, NULL, NULL, NULL, '{"imported_from": "Mariam Accounts (3).xlsx", "import_date": "2026-06-28", "comm": "Call", "using_ats": "Yes", "ats_name": "Taleo", "proposed_plan": "Enterprise", "demo_status": null, "invoiced": false, "collected": false}'::jsonb, '2025-10-11'::date),
  ('wadi Group', 'ali sami', '+201066693505', 'LinkedIn', NULL, 'lost', true, 'No Budget', NULL, NULL, false, NULL, NULL, NULL, '{"imported_from": "Mariam Accounts (3).xlsx", "import_date": "2026-06-28", "comm": "Call", "using_ats": "No", "ats_name": null, "proposed_plan": null, "demo_status": null, "invoiced": false, "collected": false}'::jsonb, '2025-10-11'::date),
  ('outsourcy', 'dalia refee', '+201007886332', NULL, NULL, 'mql', false, NULL, NULL, NULL, false, NULL, NULL, NULL, '{"imported_from": "Mariam Accounts (3).xlsx", "import_date": "2026-06-28", "comm": "Call", "using_ats": "Yes", "ats_name": "Zoho", "proposed_plan": null, "demo_status": "No Show", "invoiced": false, "collected": false}'::jsonb, '2025-11-11'::date),
  ('hebasaid1989@gmail.com', NULL, NULL, NULL, NULL, 'mql', false, NULL, NULL, NULL, false, NULL, NULL, NULL, '{"imported_from": "Mariam Accounts (3).xlsx", "import_date": "2026-06-28", "comm": "Call", "using_ats": "No", "ats_name": null, "proposed_plan": null, "demo_status": "No Show", "invoiced": false, "collected": false}'::jsonb, '2025-12-11'::date),
  ('Alsafy group', 'salma fadel', '+201202705469', 'Forasna', NULL, 'mql', false, NULL, NULL, NULL, false, NULL, NULL, NULL, '{"imported_from": "Mariam Accounts (3).xlsx", "import_date": "2026-06-28", "comm": "Call", "using_ats": "No", "ats_name": null, "proposed_plan": null, "demo_status": null, "invoiced": false, "collected": false}'::jsonb, '2025-02-11'::date),
  ('Red square', 'ahmed dewidar', '+201122633088', NULL, 'They already have Odoo ATS and are seeking sourcing channels instead of Wuzzuf and LinkedIn, so they decided not to proceed.', 'lost', true, 'Did not convert', 144000.0, '2025-11-25'::date, false, NULL, NULL, NULL, '{"imported_from": "Mariam Accounts (3).xlsx", "import_date": "2026-06-28", "comm": "Email", "using_ats": "No", "ats_name": null, "proposed_plan": "Enterprise", "demo_status": null, "invoiced": false, "collected": false}'::jsonb, '2025-11-13'::date),
  ('Gardenia', 'mohamed hamounda', '+201006123236', 'Launchpad Expo', NULL, 'won', false, NULL, 70000.0, '2025-11-20'::date, false, '2025-11-23'::date, 70000.0, 'Pro', '{"imported_from": "Mariam Accounts (3).xlsx", "import_date": "2026-06-28", "comm": "Call", "using_ats": "No", "ats_name": null, "proposed_plan": "Pro", "demo_status": null, "invoiced": true, "collected": true}'::jsonb, '2025-11-17'::date),
  ('Delta lighting', 'micheal', '+201119551193', NULL, NULL, 'lost', true, 'No Budget', 86400.0, '2025-11-27'::date, false, NULL, NULL, 'Pro', '{"imported_from": "Mariam Accounts (3).xlsx", "import_date": "2026-06-28", "comm": "Call", "using_ats": "No", "ats_name": null, "proposed_plan": "Pro", "demo_status": null, "invoiced": false, "collected": false}'::jsonb, '2025-11-18'::date),
  ('Garnell', NULL, NULL, NULL, NULL, 'mql', false, NULL, NULL, NULL, false, NULL, NULL, NULL, '{"imported_from": "Mariam Accounts (3).xlsx", "import_date": "2026-06-28", "comm": "Call", "using_ats": "No", "ats_name": null, "proposed_plan": null, "demo_status": "No Show", "invoiced": false, "collected": false}'::jsonb, '2025-11-18'::date),
  ('Sky holding', 'ahmed adel', '+201158098080', 'Hub Spot — Old Data', NULL, 'lost', true, 'No Budget', 70000.0, NULL, false, NULL, NULL, 'Pro', '{"imported_from": "Mariam Accounts (3).xlsx", "import_date": "2026-06-28", "comm": "Call", "using_ats": "No", "ats_name": null, "proposed_plan": "Pro", "demo_status": null, "invoiced": false, "collected": false}'::jsonb, '2025-11-19'::date),
  ('MKY', 'mahmoud', '+201011983632', 'Launchpad Expo', NULL, 'lost', true, 'on hold', 90000.0, '2025-12-10'::date, false, NULL, NULL, 'Pro', '{"imported_from": "Mariam Accounts (3).xlsx", "import_date": "2026-06-28", "comm": "Call", "using_ats": "No", "ats_name": null, "proposed_plan": "Pro", "demo_status": null, "invoiced": false, "collected": false}'::jsonb, '2025-11-25'::date),
  ('Seoudi', 'marwan bastawisy', '+201096881055', 'Renewal', NULL, 'won', false, NULL, 124000.0, NULL, false, '2025-11-26'::date, 124000.0, 'Enterprise', '{"imported_from": "Mariam Accounts (3).xlsx", "import_date": "2026-06-28", "comm": "Call", "using_ats": "Yes", "ats_name": "Recruitera", "proposed_plan": "Enterprise", "demo_status": null, "invoiced": true, "collected": false}'::jsonb, '2025-11-30'::date),
  ('Madient Masr', 'amr kamel', '+201003570095', 'Hub Spot — Old Data', NULL, 'mql', false, NULL, 185000.0, NULL, false, NULL, NULL, 'Enterprise', '{"imported_from": "Mariam Accounts (3).xlsx", "import_date": "2026-06-28", "comm": "Call", "using_ats": "No", "ats_name": null, "proposed_plan": "Enterprise", "demo_status": null, "invoiced": false, "collected": false}'::jsonb, '2025-11-26'::date),
  ('Mobco', NULL, NULL, NULL, NULL, 'mql', false, NULL, NULL, NULL, false, NULL, NULL, NULL, '{"imported_from": "Mariam Accounts (3).xlsx", "import_date": "2026-06-28", "comm": "Call", "using_ats": "No", "ats_name": null, "proposed_plan": null, "demo_status": "No Show", "invoiced": false, "collected": false}'::jsonb, '2025-11-27'::date),
  ('Abou Ghali motors', 'radwa', '+201001109966', 'Hub Spot — Old Data', 'no answer', 'lost', true, 'Missing Features', NULL, NULL, true, NULL, NULL, NULL, '{"imported_from": "Mariam Accounts (3).xlsx", "import_date": "2026-06-28", "comm": "Call", "using_ats": "Yes", "ats_name": "Zoho", "proposed_plan": "Enterprise", "demo_status": null, "invoiced": false, "collected": false}'::jsonb, '2025-12-14'::date),
  ('Organo Group', 'ali gomaa', '+201027385559', NULL, 'He is awaiting management approval and has requested that we follow up with him next Tuesday', 'lost', true, 'on hold', 86400.0, '2025-12-25'::date, false, NULL, NULL, NULL, '{"imported_from": "Mariam Accounts (3).xlsx", "import_date": "2026-06-28", "comm": "Call", "using_ats": "No", "ats_name": null, "proposed_plan": "Pro", "demo_status": null, "invoiced": false, "collected": false}'::jsonb, '2025-12-14'::date),
  ('Kahraba', 'dina', '+201222331177', 'Wuzzuf', NULL, 'mql', false, NULL, NULL, NULL, false, NULL, NULL, NULL, '{"imported_from": "Mariam Accounts (3).xlsx", "import_date": "2026-06-28", "comm": "Call", "using_ats": "No", "ats_name": null, "proposed_plan": null, "demo_status": null, "invoiced": false, "collected": false}'::jsonb, '2025-12-17'::date),
  ('Damen e payment', 'ahmed', '+201110203003', 'Hub Spot — Old Data', 'He requested to follow up with him after the first week of January to schedule a demo.', 'mql', false, NULL, NULL, NULL, false, NULL, NULL, NULL, '{"imported_from": "Mariam Accounts (3).xlsx", "import_date": "2026-06-28", "comm": "Call", "using_ats": "No", "ats_name": null, "proposed_plan": null, "demo_status": null, "invoiced": false, "collected": false}'::jsonb, '2025-12-22'::date),
  ('EYouth', 'mohamed gamal', '+201017948951', 'Hub Spot — Old Data', NULL, 'mql', false, NULL, 86400.0, '2025-12-31'::date, false, NULL, NULL, NULL, '{"imported_from": "Mariam Accounts (3).xlsx", "import_date": "2026-06-28", "comm": "Call", "using_ats": "No", "ats_name": null, "proposed_plan": "Pro", "demo_status": null, "invoiced": false, "collected": false}'::jsonb, '2025-12-23'::date),
  ('kedma dhd', 'amany', '+201154021118', 'Wuzzuf', NULL, 'mql', false, NULL, 86860.0, '2026-01-12'::date, false, NULL, NULL, NULL, '{"imported_from": "Mariam Accounts (3).xlsx", "import_date": "2026-06-28", "comm": "Call", "using_ats": "No", "ats_name": null, "proposed_plan": "Pro", "demo_status": null, "invoiced": false, "collected": false}'::jsonb, '2025-12-29'::date),
  ('Dabur', 'doaa', '+201225555856', 'Hub Spot — Old Data', NULL, 'lost', true, 'Did not convert', 84000.0, '2026-01-26'::date, false, NULL, NULL, NULL, '{"imported_from": "Mariam Accounts (3).xlsx", "import_date": "2026-06-28", "comm": null, "using_ats": null, "ats_name": null, "proposed_plan": "Pro", "demo_status": null, "invoiced": false, "collected": false}'::jsonb, '2026-01-12'::date),
  ('elsewedy-ind', 'mahmoud', '+201234500770', NULL, NULL, 'mql', false, NULL, 77000.0, '2026-01-25'::date, true, NULL, NULL, NULL, '{"imported_from": "Mariam Accounts (3).xlsx", "import_date": "2026-06-28", "comm": "Email", "using_ats": "No", "ats_name": null, "proposed_plan": "Pro", "demo_status": null, "invoiced": false, "collected": false}'::jsonb, '2026-01-13'::date),
  ('Talent360', 'samar', '+201023007992', 'Hub Spot — Old Data', NULL, 'lost', true, 'Pricing', 144000.0, NULL, false, NULL, NULL, NULL, '{"imported_from": "Mariam Accounts (3).xlsx", "import_date": "2026-06-28", "comm": "Call", "using_ats": "Yes", "ats_name": "Freshteam", "proposed_plan": "Enterprise", "demo_status": null, "invoiced": false, "collected": false}'::jsonb, '2026-01-18'::date),
  ('Fort Capital group', 'maria', '+201065555311', 'Hub Spot — Old Data', NULL, 'won', false, NULL, 153000.0, '2026-01-29'::date, false, '2026-02-03'::date, 512550.0, 'Enterprise', '{"imported_from": "Mariam Accounts (3).xlsx", "import_date": "2026-06-28", "comm": null, "using_ats": null, "ats_name": null, "proposed_plan": "Enterprise+", "demo_status": null, "invoiced": true, "collected": true}'::jsonb, '2026-01-21'::date),
  ('Rushbrush', 'ahmed helmy', '+201111114313', NULL, NULL, 'mql', false, NULL, NULL, NULL, false, NULL, 140000.0, NULL, '{"imported_from": "Mariam Accounts (3).xlsx", "import_date": "2026-06-28", "comm": "Call", "using_ats": null, "ats_name": null, "proposed_plan": null, "demo_status": "No Show", "invoiced": false, "collected": false}'::jsonb, '2026-01-28'::date),
  ('Innovasights', NULL, NULL, NULL, NULL, 'mql', false, NULL, NULL, NULL, false, NULL, NULL, NULL, '{"imported_from": "Mariam Accounts (3).xlsx", "import_date": "2026-06-28", "comm": "Call", "using_ats": null, "ats_name": null, "proposed_plan": null, "demo_status": null, "invoiced": false, "collected": false}'::jsonb, '2026-01-28'::date),
  ('Shift-ev', 'mostafa hamdi', '+201118396918', NULL, 'they need job offer module', 'lost', true, 'Missing Features', 144000.0, '2026-02-25'::date, false, NULL, NULL, NULL, '{"imported_from": "Mariam Accounts (3).xlsx", "import_date": "2026-06-28", "comm": "Email", "using_ats": "Yes", "ats_name": "ZenATS", "proposed_plan": "Enterprise", "demo_status": null, "invoiced": false, "collected": false}'::jsonb, '2026-02-01'::date),
  ('VXI', 'masry', '+201282555584', 'BD iCareer', NULL, 'mql', false, NULL, 144000.0, '2026-02-25'::date, false, NULL, NULL, NULL, '{"imported_from": "Mariam Accounts (3).xlsx", "import_date": "2026-06-28", "comm": "Email", "using_ats": "Yes", "ats_name": "Workday", "proposed_plan": "Enterprise", "demo_status": null, "invoiced": false, "collected": false}'::jsonb, '2026-02-04'::date),
  ('Alarabia Group', 'nayera', '+201003819968', 'Wuzzuf', NULL, 'lost', true, 'No Budget', 144000.0, NULL, false, '2026-02-17'::date, 144000.0, NULL, '{"imported_from": "Mariam Accounts (3).xlsx", "import_date": "2026-06-28", "comm": "Call", "using_ats": "No", "ats_name": null, "proposed_plan": "Enterprise", "demo_status": null, "invoiced": false, "collected": false}'::jsonb, '2026-02-15'::date),
  ('Alahly Sabbour', 'maha eissa', '+201278758215', 'Hub Spot — Old Data', NULL, 'mql', false, NULL, 144000.0, '2026-02-26'::date, false, NULL, NULL, NULL, '{"imported_from": "Mariam Accounts (3).xlsx", "import_date": "2026-06-28", "comm": "Call", "using_ats": "No", "ats_name": null, "proposed_plan": "Enterprise", "demo_status": null, "invoiced": false, "collected": false}'::jsonb, '2026-02-16'::date),
  ('Metro Markets', 'sally ahmed', '+201000016033', 'Hub Spot — Old Data', NULL, 'mql', false, NULL, 144000.0, '2026-02-26'::date, false, NULL, NULL, 'Enterprise', '{"imported_from": "Mariam Accounts (3).xlsx", "import_date": "2026-06-28", "comm": "Call", "using_ats": "No", "ats_name": null, "proposed_plan": "Enterprise", "demo_status": null, "invoiced": false, "collected": false}'::jsonb, '2026-02-16'::date),
  ('Hassan Allam Holding', 'ahmed demerdash', '+201203756424', 'Hub Spot — Old Data', NULL, 'won', false, NULL, 630000.0, NULL, false, '2026-02-17'::date, 630000.0, 'Enterprise+', '{"imported_from": "Mariam Accounts (3).xlsx", "import_date": "2026-06-28", "comm": "Call", "using_ats": "No", "ats_name": null, "proposed_plan": "Enterprise+", "demo_status": null, "invoiced": true, "collected": false}'::jsonb, '2026-02-17'::date),
  ('Kortech', 'ahmed demerdash', '+201203756424', 'Hub Spot — Old Data', NULL, 'won', false, NULL, 180000.0, NULL, false, '2026-02-17'::date, 180000.0, 'Enterprise', '{"imported_from": "Mariam Accounts (3).xlsx", "import_date": "2026-06-28", "comm": "Call", "using_ats": "No", "ats_name": null, "proposed_plan": "Enterprise", "demo_status": null, "invoiced": true, "collected": false}'::jsonb, '2026-02-17'::date),
  ('Crossworkers-Egypt', 'amira bakr', '+201110499244', 'Wuzzuf', NULL, 'mql', false, NULL, NULL, NULL, false, NULL, NULL, NULL, '{"imported_from": "Mariam Accounts (3).xlsx", "import_date": "2026-06-28", "comm": "Call", "using_ats": "No", "ats_name": null, "proposed_plan": null, "demo_status": null, "invoiced": false, "collected": false}'::jsonb, '2026-02-18'::date),
  ('Nahdet Misr Group', 'amr algohary', '+201223894392', 'Hub Spot — Old Data', NULL, 'mql', false, NULL, NULL, NULL, false, NULL, NULL, NULL, '{"imported_from": "Mariam Accounts (3).xlsx", "import_date": "2026-06-28", "comm": "Email", "using_ats": "Yes", "ats_name": "Zoho", "proposed_plan": null, "demo_status": null, "invoiced": false, "collected": false}'::jsonb, '2026-02-22'::date),
  ('Indomie egypt', 'fayrouz', '+201006007789', 'LinkedIn', NULL, 'mql', false, NULL, NULL, NULL, false, NULL, NULL, NULL, '{"imported_from": "Mariam Accounts (3).xlsx", "import_date": "2026-06-28", "comm": null, "using_ats": "No", "ats_name": null, "proposed_plan": null, "demo_status": null, "invoiced": false, "collected": false}'::jsonb, '2026-02-22'::date),
  ('Groovy Aesthetic clinics', 'youstina', '+201011350596', 'HR Referral (Raghda)', NULL, 'mql', false, NULL, NULL, NULL, false, NULL, NULL, NULL, '{"imported_from": "Mariam Accounts (3).xlsx", "import_date": "2026-06-28", "comm": "Call", "using_ats": "No", "ats_name": null, "proposed_plan": null, "demo_status": null, "invoiced": false, "collected": false}'::jsonb, '2026-03-03'::date),
  ('hudel', 'shady saleh', '+201026050025', 'Wuzzuf', NULL, 'won', false, NULL, 91900.0, '2026-03-15'::date, false, '2026-03-17'::date, 91900.0, 'Pro', '{"imported_from": "Mariam Accounts (3).xlsx", "import_date": "2026-06-28", "comm": "Call", "using_ats": "No", "ats_name": null, "proposed_plan": "Pro", "demo_status": null, "invoiced": true, "collected": true}'::jsonb, '2026-03-04'::date),
  ('Asfour crystal', NULL, NULL, 'HR Referral (Raghda)', NULL, 'mql', false, NULL, NULL, NULL, false, NULL, NULL, NULL, '{"imported_from": "Mariam Accounts (3).xlsx", "import_date": "2026-06-28", "comm": "Call", "using_ats": null, "ats_name": null, "proposed_plan": null, "demo_status": null, "invoiced": false, "collected": false}'::jsonb, '2026-03-11'::date),
  ('Rock Developments', NULL, NULL, 'HR Referral (Raghda)', NULL, 'mql', false, NULL, NULL, NULL, false, NULL, NULL, NULL, '{"imported_from": "Mariam Accounts (3).xlsx", "import_date": "2026-06-28", "comm": "Linkedin Msg", "using_ats": null, "ats_name": null, "proposed_plan": null, "demo_status": null, "invoiced": false, "collected": false}'::jsonb, '2026-03-11'::date),
  ('midea group', 'mohamed amir', '+201227033064', 'LinkedIn', NULL, 'mql', false, NULL, NULL, NULL, false, NULL, NULL, NULL, '{"imported_from": "Mariam Accounts (3).xlsx", "import_date": "2026-06-28", "comm": null, "using_ats": null, "ats_name": null, "proposed_plan": null, "demo_status": null, "invoiced": false, "collected": false}'::jsonb, '2026-03-11'::date),
  ('Pyramakerz', 'mayar', '+201111735455', 'Wuzzuf', NULL, 'mql', false, NULL, NULL, NULL, false, NULL, NULL, NULL, '{"imported_from": "Mariam Accounts (3).xlsx", "import_date": "2026-06-28", "comm": null, "using_ats": null, "ats_name": null, "proposed_plan": null, "demo_status": null, "invoiced": false, "collected": false}'::jsonb, '2026-03-24'::date),
  ('egyproperty', NULL, NULL, NULL, NULL, 'mql', false, NULL, NULL, NULL, false, NULL, NULL, NULL, '{"imported_from": "Mariam Accounts (3).xlsx", "import_date": "2026-06-28", "comm": null, "using_ats": "No", "ats_name": null, "proposed_plan": null, "demo_status": null, "invoiced": false, "collected": false}'::jsonb, '2026-03-25'::date),
  ('Sectors Construction', 'lamiaa', '+201119941946', NULL, NULL, 'lost', true, 'Unreachable', 144000.0, '2026-04-30'::date, true, NULL, NULL, NULL, '{"imported_from": "Mariam Accounts (3).xlsx", "import_date": "2026-06-28", "comm": "Email", "using_ats": "No", "ats_name": null, "proposed_plan": "Enterprise", "demo_status": null, "invoiced": false, "collected": false}'::jsonb, '2026-03-29'::date),
  ('Larz Developments', 'mayar', '+201100037116', 'LinkedIn', NULL, 'mql', false, NULL, NULL, NULL, false, NULL, NULL, NULL, '{"imported_from": "Mariam Accounts (3).xlsx", "import_date": "2026-06-28", "comm": "Call", "using_ats": null, "ats_name": null, "proposed_plan": null, "demo_status": null, "invoiced": false, "collected": false}'::jsonb, '2026-03-30'::date),
  ('Bedinroom', 'mahmoud', '+201227910306', NULL, NULL, 'lost', true, 'Unreachable', 144000.0, '2026-04-12'::date, false, NULL, NULL, NULL, '{"imported_from": "Mariam Accounts (3).xlsx", "import_date": "2026-06-28", "comm": "Call", "using_ats": "No", "ats_name": null, "proposed_plan": "Enterprise", "demo_status": null, "invoiced": false, "collected": false}'::jsonb, '2026-03-31'::date),
  ('Madaar Developments', 'menna rageb', '+201070944733', 'LinkedIn', NULL, 'mql', false, NULL, NULL, NULL, false, NULL, NULL, NULL, '{"imported_from": "Mariam Accounts (3).xlsx", "import_date": "2026-06-28", "comm": "Call", "using_ats": null, "ats_name": null, "proposed_plan": null, "demo_status": null, "invoiced": false, "collected": false}'::jsonb, '2026-03-31'::date),
  ('AL Doha Foods', NULL, NULL, 'LinkedIn', NULL, 'mql', false, NULL, NULL, NULL, false, NULL, NULL, NULL, '{"imported_from": "Mariam Accounts (3).xlsx", "import_date": "2026-06-28", "comm": "Call", "using_ats": null, "ats_name": null, "proposed_plan": null, "demo_status": null, "invoiced": false, "collected": false}'::jsonb, '2026-04-01'::date),
  ('Mahgoub', 'mohamed adel', '+201129577786', 'Hub Spot — Old Data', NULL, 'lost', true, 'No Budget', 93000.0, '2026-04-30'::date, false, NULL, NULL, NULL, '{"imported_from": "Mariam Accounts (3).xlsx", "import_date": "2026-06-28", "comm": "Call", "using_ats": "No", "ats_name": null, "proposed_plan": "Pro", "demo_status": null, "invoiced": false, "collected": false}'::jsonb, '2026-04-01'::date),
  ('Yes Pac Packaging Solutions', 'abdalrahman', '+201201554087', NULL, NULL, 'lost', true, 'Did not convert', 432000.0, '2026-06-09'::date, true, NULL, NULL, NULL, '{"imported_from": "Mariam Accounts (3).xlsx", "import_date": "2026-06-28", "comm": "Call", "using_ats": "Yes", "ats_name": "Zoho", "proposed_plan": "Enterprise+", "demo_status": null, "invoiced": false, "collected": false}'::jsonb, '2026-04-06'::date),
  ('skyline', NULL, NULL, NULL, NULL, 'mql', false, NULL, NULL, NULL, false, NULL, NULL, NULL, '{"imported_from": "Mariam Accounts (3).xlsx", "import_date": "2026-06-28", "comm": "Call", "using_ats": "No", "ats_name": null, "proposed_plan": null, "demo_status": "No Show", "invoiced": false, "collected": false}'::jsonb, '2026-04-06'::date),
  ('onecard', 'omar', '+201140099646', NULL, NULL, 'lost', true, 'on hold', 86400.0, '2026-04-30'::date, false, NULL, NULL, NULL, '{"imported_from": "Mariam Accounts (3).xlsx", "import_date": "2026-06-28", "comm": "Email", "using_ats": null, "ats_name": null, "proposed_plan": "Pro", "demo_status": null, "invoiced": false, "collected": false}'::jsonb, '2026-04-07'::date),
  ('Sharapet', 'mai tahon', '+201202151223', NULL, NULL, 'lost', true, 'No Budget', 86400.0, '2026-04-30'::date, false, NULL, NULL, NULL, '{"imported_from": "Mariam Accounts (3).xlsx", "import_date": "2026-06-28", "comm": "Call", "using_ats": null, "ats_name": null, "proposed_plan": "Pro", "demo_status": null, "invoiced": false, "collected": false}'::jsonb, '2026-04-08'::date),
  ('Techlaz', 'rofael waheeb', '+201286039433', NULL, NULL, 'lost', true, 'Unreachable', 86400.0, '2026-04-30'::date, false, NULL, NULL, NULL, '{"imported_from": "Mariam Accounts (3).xlsx", "import_date": "2026-06-28", "comm": "Call", "using_ats": "No", "ats_name": null, "proposed_plan": "Pro", "demo_status": null, "invoiced": false, "collected": false}'::jsonb, '2026-04-08'::date),
  ('EGMI group', 'mohamed fawzy', '+201028118029', NULL, NULL, 'lost', true, 'No Budget', 55000.0, '2026-04-20'::date, false, NULL, NULL, NULL, '{"imported_from": "Mariam Accounts (3).xlsx", "import_date": "2026-06-28", "comm": "Call", "using_ats": null, "ats_name": null, "proposed_plan": "Basic", "demo_status": null, "invoiced": false, "collected": false}'::jsonb, '2026-04-08'::date),
  ('TLD', 'islam gabal', '+201070992929', NULL, NULL, 'lost', true, 'on hold', 144000.0, '2026-04-30'::date, false, NULL, NULL, NULL, '{"imported_from": "Mariam Accounts (3).xlsx", "import_date": "2026-06-28", "comm": "Email", "using_ats": "Yes", "ats_name": "ZenATS", "proposed_plan": "Enterprise", "demo_status": null, "invoiced": false, "collected": false}'::jsonb, '2026-04-14'::date),
  ('Nok', 'menna', '+201222197058', 'Akram (Referral)', NULL, 'mql', false, NULL, 600000.0, '2026-05-07'::date, false, NULL, NULL, NULL, '{"imported_from": "Mariam Accounts (3).xlsx", "import_date": "2026-06-28", "comm": "Email", "using_ats": "Yes", "ats_name": "Mental", "proposed_plan": "Enterprise+", "demo_status": null, "invoiced": false, "collected": false}'::jsonb, '2026-04-14'::date),
  ('Nawy', 'esraa', '+201555536696', 'LinkedIn', NULL, 'mql', false, NULL, NULL, NULL, false, NULL, NULL, NULL, '{"imported_from": "Mariam Accounts (3).xlsx", "import_date": "2026-06-28", "comm": null, "using_ats": null, "ats_name": null, "proposed_plan": null, "demo_status": null, "invoiced": false, "collected": false}'::jsonb, '2026-04-15'::date),
  ('Tracks', 'eman', '+966549837948', NULL, NULL, 'mql', false, NULL, 55000.0, '2026-04-30'::date, false, NULL, NULL, NULL, '{"imported_from": "Mariam Accounts (3).xlsx", "import_date": "2026-06-28", "comm": "Email", "using_ats": "No", "ats_name": null, "proposed_plan": "Basic", "demo_status": null, "invoiced": false, "collected": false}'::jsonb, '2026-04-20'::date),
  ('Axis', 'eslam', '+201004909460', 'Akram (Referral)', NULL, 'mql', false, NULL, 49500.0, '2026-05-31'::date, true, NULL, NULL, NULL, '{"imported_from": "Mariam Accounts (3).xlsx", "import_date": "2026-06-28", "comm": "Email", "using_ats": "Yes", "ats_name": "ZenATS", "proposed_plan": "Basic", "demo_status": null, "invoiced": false, "collected": false}'::jsonb, '2026-04-20'::date),
  ('max360', 'dalia atef', '+201119280755', NULL, NULL, 'mql', false, NULL, 144000.0, '2026-05-17'::date, false, NULL, NULL, NULL, '{"imported_from": "Mariam Accounts (3).xlsx", "import_date": "2026-06-28", "comm": "Call", "using_ats": "Yes", "ats_name": "ZenATS", "proposed_plan": "Enterprise", "demo_status": null, "invoiced": false, "collected": false}'::jsonb, '2026-04-26'::date),
  ('enableoutsourcing', 'hany zaher', '+201221124080', NULL, NULL, 'mql', false, NULL, 144000.0, '2026-05-17'::date, false, NULL, NULL, NULL, '{"imported_from": "Mariam Accounts (3).xlsx", "import_date": "2026-06-28", "comm": "Call", "using_ats": "No", "ats_name": null, "proposed_plan": "Enterprise", "demo_status": null, "invoiced": false, "collected": false}'::jsonb, '2026-04-30'::date),
  ('Delta Masr Group', 'islam kamal', '+201022736002', NULL, NULL, 'mql', false, NULL, 86400.0, '2026-05-14'::date, false, NULL, NULL, NULL, '{"imported_from": "Mariam Accounts (3).xlsx", "import_date": "2026-06-28", "comm": "Call", "using_ats": null, "ats_name": null, "proposed_plan": "Pro", "demo_status": null, "invoiced": false, "collected": false}'::jsonb, '2026-05-03'::date),
  ('Mavens Consulting', 'mohamed moataz', '+201069849050', 'CFYE', NULL, 'won', false, NULL, 195000.0, '2026-05-25'::date, false, '2026-05-18'::date, 195000.0, 'Enterprise+', '{"imported_from": "Mariam Accounts (3).xlsx", "import_date": "2026-06-28", "comm": "Email", "using_ats": null, "ats_name": null, "proposed_plan": "Enterprise+", "demo_status": null, "invoiced": false, "collected": false}'::jsonb, '2026-05-10'::date),
  ('widebot', 'maha zaki', '+201000598358', NULL, NULL, 'mql', false, NULL, 86400.0, '2026-05-25'::date, false, NULL, NULL, NULL, '{"imported_from": "Mariam Accounts (3).xlsx", "import_date": "2026-06-28", "comm": "Call", "using_ats": null, "ats_name": null, "proposed_plan": "Pro", "demo_status": null, "invoiced": false, "collected": false}'::jsonb, '2026-05-10'::date),
  ('Concrete', 'mariam', '+201005400282', 'Launchpad Expo', NULL, 'mql', false, NULL, 86400.0, '2026-06-10'::date, false, NULL, NULL, NULL, '{"imported_from": "Mariam Accounts (3).xlsx", "import_date": "2026-06-28", "comm": "Call", "using_ats": null, "ats_name": null, "proposed_plan": "Pro", "demo_status": null, "invoiced": false, "collected": false}'::jsonb, '2026-05-19'::date),
  ('bosta', 'menna abdalkhaik', '+201112615659', 'LinkedIn', NULL, 'mql', false, NULL, NULL, NULL, false, NULL, NULL, NULL, '{"imported_from": "Mariam Accounts (3).xlsx", "import_date": "2026-06-28", "comm": "Call", "using_ats": null, "ats_name": null, "proposed_plan": null, "demo_status": null, "invoiced": false, "collected": false}'::jsonb, '2026-06-02'::date),
  ('saudia catering', 'mohamed', '0', NULL, NULL, 'mql', false, NULL, 86400.0, '2026-06-15'::date, false, NULL, NULL, NULL, '{"imported_from": "Mariam Accounts (3).xlsx", "import_date": "2026-06-28", "comm": "Email", "using_ats": "Yes", "ats_name": "SuccessFactors", "proposed_plan": "Pro", "demo_status": null, "invoiced": false, "collected": false}'::jsonb, '2026-06-03'::date),
  ('Zero Carbon', 'dina', '+201211182900', 'Launchpad Expo', NULL, 'mql', false, NULL, 49500.0, NULL, false, NULL, NULL, NULL, '{"imported_from": "Mariam Accounts (3).xlsx", "import_date": "2026-06-28", "comm": "Call", "using_ats": "No", "ats_name": null, "proposed_plan": "Basic", "demo_status": null, "invoiced": false, "collected": false}'::jsonb, '2026-06-03'::date),
  ('Reckitt', 'bassant', '+201147852470', 'Akram (Referral)', NULL, 'mql', false, NULL, 96000.0, NULL, false, NULL, NULL, NULL, '{"imported_from": "Mariam Accounts (3).xlsx", "import_date": "2026-06-28", "comm": "Call", "using_ats": "No", "ats_name": null, "proposed_plan": null, "demo_status": null, "invoiced": false, "collected": false}'::jsonb, '2026-06-09'::date);

UPDATE accounts a SET
  am_mail   = 'mariam.samir@recruitera.ai',
  owner_id  = COALESCE(a.owner_id, 'f494e81a-81c6-4e2a-ba7d-1366dbd9ef62'::uuid),
  source    = COALESCE(NULLIF(a.source,''), i.source),
  deal_value = COALESCE(a.deal_value, i.proposed_amount),
  close_date = COALESCE(a.close_date, i.deadline),
  has_trial = a.has_trial OR i.has_trial,
  is_disqualified = CASE WHEN i.is_disq THEN true ELSE a.is_disqualified END,
  disq_reason     = COALESCE(NULLIF(a.disq_reason,''), i.disq_reason),
  paid_status     = CASE WHEN i.stage='won' AND a.paid_status IS NULL THEN 'Paid' ELSE a.paid_status END,
  activation_status = CASE WHEN i.stage='won' AND a.activation_status IS NULL THEN 'Active' ELSE a.activation_status END,
  stage = CASE
    WHEN i.is_disq AND NOT a.is_disqualified THEN i.stage::pipeline_stage
    WHEN i.stage = 'won'  AND a.stage::text NOT IN ('won','lost') THEN 'won'::pipeline_stage
    WHEN i.stage = 'lost' AND a.stage::text NOT IN ('won','lost') THEN 'lost'::pipeline_stage
    WHEN i.stage = 'sql'  AND a.stage::text IN ('lead','mql') THEN 'sql'::pipeline_stage
    WHEN i.stage = 'mql'  AND a.stage::text = 'lead' THEN 'mql'::pipeline_stage
    ELSE a.stage
  END,
  raw_data = a.raw_data || i.raw_extra
FROM _import i WHERE lower(trim(a.name)) = lower(trim(i.company));

INSERT INTO accounts (name, stage, source, am_mail, owner_id, bubble_id, raw_data,
  deal_value, close_date, has_trial, is_disqualified, disq_reason,
  paid_status, activation_status, bubble_created_at)
SELECT i.company, i.stage::pipeline_stage, i.source,
  'mariam.samir@recruitera.ai', 'f494e81a-81c6-4e2a-ba7d-1366dbd9ef62'::uuid,
  'manual_import_' || substr(md5(i.company || clock_timestamp()::text), 1, 16),
  i.raw_extra, i.proposed_amount, i.deadline, i.has_trial,
  i.is_disq, i.disq_reason,
  CASE WHEN i.stage='won' THEN 'Paid' ELSE NULL END,
  CASE WHEN i.stage='won' THEN 'Active' ELSE NULL END,
  COALESCE(i.sheet_date, now()::date)
FROM _import i
WHERE NOT EXISTS (SELECT 1 FROM accounts a WHERE lower(trim(a.name)) = lower(trim(i.company)));

UPDATE accounts a SET am_mail = 'mariam.samir@recruitera.ai', owner_id = 'f494e81a-81c6-4e2a-ba7d-1366dbd9ef62'::uuid
FROM _import i WHERE lower(trim(a.name)) = lower(trim(i.company))
  AND (a.am_mail IS DISTINCT FROM 'mariam.samir@recruitera.ai' OR a.owner_id IS DISTINCT FROM 'f494e81a-81c6-4e2a-ba7d-1366dbd9ef62'::uuid);

INSERT INTO contacts (account_id, full_name, phone, is_primary)
SELECT a.id, NULLIF(trim(i.contact_name),''), NULLIF(trim(i.contact_phone),''), true
FROM _import i
JOIN accounts a ON lower(trim(a.name)) = lower(trim(i.company))
WHERE (NULLIF(trim(i.contact_name),'') IS NOT NULL OR NULLIF(trim(i.contact_phone),'') IS NOT NULL)
  AND NOT EXISTS (SELECT 1 FROM contacts c WHERE c.account_id = a.id);

INSERT INTO activities (account_id, author_id, type, text)
SELECT a.id, 'f494e81a-81c6-4e2a-ba7d-1366dbd9ef62'::uuid, 'note',
  E'Imported from sheet (Mariam Accounts.xlsx, Jun 28 2026)\n\n' ||
  CASE WHEN i.notes IS NULL OR i.notes='' THEN '(no notes in sheet)' ELSE i.notes END
FROM _import i JOIN accounts a ON lower(trim(a.name)) = lower(trim(i.company));

INSERT INTO contract_cycles (account_id, started_at, ends_at, value, currency, plan_tier, status, cycle_number)
SELECT a.id, COALESCE(i.conversion_date, now()::date),
  (COALESCE(i.conversion_date, now()::date) + interval '1 year')::date,
  i.amount, 'EGP', i.plan_tier, 'active', 1
FROM _import i JOIN accounts a ON lower(trim(a.name)) = lower(trim(i.company))
WHERE i.stage = 'won' AND NOT EXISTS (SELECT 1 FROM contract_cycles c WHERE c.account_id = a.id);
